# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f847c18b9f2ed24cbaf0cf276b27f8192081393602ca53686792ad19b3939bc8aa53d92c85ca83ebdfdd3755fac9e0aae933cf949386bd73d3a270e07f3e4ac

test:
  secret_key_base: a610ec708585aa7a33632dcacdeb54bdab26679be873728f0521dc690a19a8bf297e80687129d44330f30cc0fa9498938f717dc9c249bb24dac9b5010d07e91c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
